apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno
  namespace: kyverno
status:
  availableReplicas: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
---
apiVersion: v1
kind: Pod
metadata:
  namespace: kyverno
status:
  phase: Running
---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-svc
  namespace: kyverno
---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-svc-metrics
  namespace: kyverno
